### ISSUE TITLE
np.float deprecated in latest numpy

### ISSUE THREAD

**Issue by ernewton** [tofflemire/saphires#1]
File ~/opt/anaconda3/envs/salt-hrs/lib/python3.12/site-packages/saphires/io.py:570, in read_fits(spectra_list, temp, w_mult, combine_all, norm, trim_style, norm_w_width, norm_maxiter, norm_lower, norm_upper, norm_nord)
    568 t_hdulist=pyfits.open(t_f_names[i])
    569 t_flux=t_hdulist[0].data
--> 570 t_w0=np.float(t_hdulist[0].header['CRVAL1'])
    571 t_dw=np.float(t_hdulist[0].header['CDELT1'])
    573 if 'LTV1' in t_hdulist[0].header:

File ~/opt/anaconda3/envs/salt-hrs/lib/python3.12/site-packages/numpy/__init__.py:324, in __getattr__(attr)
    319     warnings.warn(
    320         f"In the future `np.{attr}` will be defined as the "
    321         "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    323 if attr in __former_attrs__:
--> 324     raise AttributeError(__former_attrs__[attr])
    326 if attr == 'testing':
    327     import numpy.testing as testing

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by ernewton** [comment]
Also np.str:

AttributeError                            Traceback (most recent call last)
Cell In[24], line 1
----> 1 temp = saph.io.read_pkl('/Users/enewton/PHOENIX/saphires/logg4.5/lte03400-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_2800-11000_air.p',temp=True,norm_w_width=200)

File ~/opt/anaconda3/envs/salt-hrs/lib/python3.12/site-packages/saphires/io.py:313, in read_pkl(spectra_list, temp, combine_all, norm, w_mult, trim_style, dk_wav, dk_flux, norm_w_width, norm_maxiter, norm_lower, norm_upper, norm_nord)
    310 t_w = t_w*w_mult
    312 if in_type in direct:
--> 313 	w_range_out = np.str(np.int(np.min(t_w)))+'-'+np.str(np.int(np.max(t_w)))
    314 if in_type in ord_list:
    315 	if w_range[j] == '*':

File ~/opt/anaconda3/envs/salt-hrs/lib/python3.12/site-packages/numpy/__init__.py:324, in __getattr__(attr)
    319     warnings.warn(
    320         f"In the future `np.{attr}` will be defined as the "
    321         "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    323 if attr in __former_attrs__:
--> 324     raise AttributeError(__former_attrs__[attr])
    326 if attr == 'testing':
    327     import numpy.testing as testing

AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by tofflemire** [comment]
Both should be resolved in the new pypi (pip) release, version 0.1.17
